name = "visual-feedback-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[env.production]
name = "visual-feedback-api-prod"

[[d1_databases]]
binding = "DB"
database_name = "visual-feedback-db"
database_id = "2829e7aa-0473-49b2-881b-8b17c702aa06"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "visual-feedback-images"
